Added Global Strings and removed hardcoded strings for directions.
The-Robotics-Forum/netra pull request #89
Opened 2021-12-08 10:32 UTC by debz-g

# Description

-Removed hardcoded Strings.
-Fixed Right Direction button not showing status.

# Checklist

Please make sure to mark these checkboxes

- [yes] Ran `gradlew build check` or `./gradlew build check` successfully

- [yes] Squashed Commits

2021-12-10 05:06 UTC, avinash14022002 commented on app/build.gradle
> +    buildFeatures {
Remove the dependency for view binding

2021-12-10 05:07 UTC, avinash14022002 requested changes
@debz-g checkout the comment

2021-12-10 14:18 UTC, debz-g commented on app/build.gradle
> +    buildFeatures {
I have removed it.

2021-12-14 05:49 UTC, avinash14022002 approved these changes

2021-12-14 05:49 UTC, merged